(define (make-account balance account-password)
  (define (withdraw amount)
    (if (<= amount balance)
        (begin (set! balance (- balance amount))
               balance)
        (error "Insufficient funds")))

  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)

  (define (call-the-cops)
    (error "Calling the cops..."))

  (let ((fail-count 0))
    (define (dispatch password m)
      (if (eq? password account-password)
        (begin (set! fail-count 0)
               (cond ((eq? m 'withdraw) withdraw)
                     ((eq? m 'deposit) deposit)
                     (else (error "Unknown request: MAKE-ACCOUNT" m))))
        (begin (set! fail-count (+ 1 fail-count))
               (if (>= fail-count 7)
                   (call-the-cops)
                   (lambda (amount) (error "Incorrect password"))))))
    dispatch))